title: My Jekyll Site
author: Your Name
email: your-email@example.com
description: A beautiful Jekyll site

# For a project page, use:
# baseurl: "/repository-name"
# For a user/organization page, use:
baseurl: ""

# Update this with your GitHub username
url: "https://USERNAME.github.io"

# Build settings
markdown: kramdown
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Development settings
host: 0.0.0.0
port: 8080
livereload: false
serving: true
detach: false
